spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://117.78.8.44:3306/pilipili?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
      username: remote_user
      password: lcp1
      max-active: 200
      initial-size: 10
      max-wait: 100000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

my:
  project:
    param:
      head-img: /assets/images/background.jpeg
      salt: llccpp
      code:
        expiration-time: 120
    user:
      head-img:
        resource-location: E:/headImg/
        resource-handler: /img/head/